# /// script
# requires-python = ">=3.12"
# dependencies = ["pyyaml>=6.0.1"]
# ///
"""Generate `index.md` for a research directory from its `index.yaml`.

`index.md` is the Obsidian-readable view of the canonical `index.yaml`. It uses
Obsidian `[[wikilinks]]` so the graph view lights up. It is regenerated at the
end of every operation that mutates `index.yaml` and must NEVER be hand-edited.

Behavior:
  - Reads <research-dir>/index.yaml.
  - Lists wiki pages found on disk under <research-dir>/wiki/ (overview,
    synthesis, entities/, concepts/, comparisons/, questions/, open-questions,
    contradictions, repos/, renders/).
  - Lists sources from index.yaml grouped by category (seeds first, then by
    origin).
  - Output is deterministic: identical inputs (yaml + wiki tree) produce
    byte-identical output.

Usage:
  uv run --script scripts/build_index_md.py --research-dir /path/to/research-<slug>
  # or:
  uv run --script scripts/build_index_md.py \\
    --index-yaml /path/to/research-<slug>/index.yaml \\
    --output /path/to/research-<slug>/index.md \\
    --wiki-dir /path/to/research-<slug>/wiki
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

HEADER = (
    "<!-- AUTOGENERATED from index.yaml. Do not edit. Run /research, /research-lint, or scripts/build_index_md.py to regenerate. -->\n\n"
)


# ----- helpers --------------------------------------------------------------


def first_sentence(text: str | None) -> str:
    if not text:
        return ""
    text = text.strip()
    for terminator in [". ", ".\n", "! ", "? "]:
        if terminator in text:
            return text.split(terminator, 1)[0].rstrip(".!?") + "."
    return text if len(text) <= 200 else text[:197] + "..."


def wikilink(path: str, label: str | None = None) -> str:
    """Render an Obsidian wikilink. Strip .md so the link resolves cleanly."""
    target = path[:-3] if path.endswith(".md") else path
    if label and label != target:
        return f"[[{target}|{label}]]"
    return f"[[{target}]]"


def sorted_md_files(directory: Path) -> list[Path]:
    if not directory.is_dir():
        return []
    return sorted(p for p in directory.iterdir() if p.is_file() and p.suffix == ".md")


# ----- wiki section ---------------------------------------------------------


def render_wiki_section(wiki_dir: Path) -> str:
    """List every wiki page found on disk, grouped by type. Stable order."""
    if not wiki_dir.is_dir():
        return ""

    parts: list[str] = ["## Wiki pages\n"]

    # Top-level singletons in a fixed order.
    singletons = [
        ("overview.md", "Overview"),
        ("synthesis.md", "Synthesis"),
        ("open-questions.md", "Open questions"),
        ("contradictions.md", "Contradictions"),
    ]
    top_lines = []
    for filename, label in singletons:
        if (wiki_dir / filename).is_file():
            top_lines.append(f"- {wikilink(f'wiki/{filename}', label)}")
    if top_lines:
        parts.append("\n".join(top_lines) + "\n")

    # Subdirectories — entities, concepts, comparisons, questions, sources, repos, renders.
    subdir_specs = [
        ("sources", "Sources (per-source pages)"),
        ("entities", "Entities"),
        ("concepts", "Concepts"),
        ("comparisons", "Comparisons"),
        ("questions", "Questions"),
    ]
    for subdir_name, heading in subdir_specs:
        files = sorted_md_files(wiki_dir / subdir_name)
        if not files:
            continue
        parts.append(f"\n### {heading}\n")
        lines = [f"- {wikilink(f'wiki/{subdir_name}/{f.name}', f.stem)}" for f in files]
        parts.append("\n".join(lines) + "\n")

    # repos/ — one entry per repo subfolder.
    repos_dir = wiki_dir / "repos"
    if repos_dir.is_dir():
        repo_dirs = sorted(d for d in repos_dir.iterdir() if d.is_dir())
        if repo_dirs:
            parts.append("\n### Repos\n")
            lines = []
            for repo in repo_dirs:
                arch = repo / "ARCHITECTURE.md"
                if arch.is_file():
                    lines.append(f"- {wikilink(f'wiki/repos/{repo.name}/ARCHITECTURE.md', repo.name)}")
            if lines:
                parts.append("\n".join(lines) + "\n")

    # renders/ — grouped by format.
    renders_dir = wiki_dir / "renders"
    if renders_dir.is_dir():
        format_dirs = sorted(d for d in renders_dir.iterdir() if d.is_dir())
        rendered_lines = []
        for fmt_dir in format_dirs:
            files = sorted(f for f in fmt_dir.iterdir() if f.is_file())
            for f in files:
                # Skip companion .py scripts for charts; the .png is the render.
                if fmt_dir.name == "charts" and f.suffix == ".py":
                    continue
                rendered_lines.append(f"- ({fmt_dir.name}) {wikilink(f'wiki/renders/{fmt_dir.name}/{f.name}', f.stem)}")
        if rendered_lines:
            parts.append("\n### Renders\n")
            parts.append("\n".join(rendered_lines) + "\n")

    return "".join(parts) + "\n---\n\n"


# ----- sources section ------------------------------------------------------


SEED_SCORE = 1.0


def group_sources(sources: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    groups: dict[str, list[dict[str, Any]]] = {"seeds": []}
    for src in sources:
        if (src.get("relevance_score") or 0.0) >= SEED_SCORE:
            groups["seeds"].append(src)
        else:
            origin = src.get("origin") or "other"
            groups.setdefault(origin, []).append(src)
    return groups


def render_source_line(src: dict[str, Any]) -> str:
    title = src.get("title") or "Untitled"
    score = src.get("relevance_score")
    origin = src.get("origin") or "?"
    score_str = f"{score:.2f}" if isinstance(score, (int, float)) else "?"

    uri_full = src.get("uri_full")
    label = title
    if uri_full:
        link = wikilink(uri_full, label)
    else:
        link = title  # nothing to link to

    summary_snippet = first_sentence(src.get("summary"))

    extras = []
    if src.get("readwise_location"):
        extras.append(f"loc: {src['readwise_location']}")
    if src.get("nlm_notebook_title"):
        extras.append(f"notebook: {src['nlm_notebook_title']}")
    if src.get("github_repo_url"):
        extras.append("repo")
    extras_str = f" [{', '.join(extras)}]" if extras else ""

    head = f"- {link} (score: {score_str}, {origin}){extras_str}"
    if summary_snippet:
        return f"{head} — {summary_snippet}"
    return head


def render_sources_section(sources: list[dict[str, Any]]) -> str:
    if not sources:
        return "## Sources\n\n_No sources indexed._\n"
    groups = group_sources(sources)

    # Stable category order: seeds first, then origins alphabetically.
    ordered_categories = ["seeds"] + sorted(k for k in groups if k != "seeds")

    parts: list[str] = ["## Sources\n"]
    for category in ordered_categories:
        items = groups.get(category) or []
        if not items:
            continue
        # Stable order within category: by score desc, then title.
        items_sorted = sorted(
            items,
            key=lambda s: (
                -(s.get("relevance_score") or 0.0),
                (s.get("title") or "").lower(),
            ),
        )
        heading = "Seeds (user-provided)" if category == "seeds" else category.capitalize()
        parts.append(f"\n### {heading} ({len(items_sorted)})\n")
        parts.append("\n".join(render_source_line(s) for s in items_sorted) + "\n")

    return "".join(parts)


# ----- main -----------------------------------------------------------------


def build_md(index_yaml_path: Path, wiki_dir: Path) -> str:
    doc = yaml.safe_load(index_yaml_path.read_text()) or {}
    topic = doc.get("topic") or "Untitled research"
    input_summary = doc.get("input_summary") or ""
    total = doc.get("total_sources")
    sources = doc.get("sources") or []

    parts: list[str] = [HEADER]
    parts.append(f"# {topic}\n\n")
    if input_summary:
        parts.append(f"> {input_summary}\n\n")

    meta_lines: list[str] = []
    if doc.get("created"):
        meta_lines.append(f"- Created: `{doc['created']}`")
    if doc.get("last_updated"):
        meta_lines.append(f"- Last updated: `{doc['last_updated']}`")
    if total is not None:
        meta_lines.append(f"- Total sources: {total}")
    if doc.get("rounds_completed") is not None:
        meta_lines.append(f"- Rounds completed: {doc['rounds_completed']}")
    if meta_lines:
        parts.append("\n".join(meta_lines) + "\n\n---\n\n")

    parts.append(render_wiki_section(wiki_dir))
    parts.append(render_sources_section(sources))

    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--research-dir",
        help="Path to the research dir (uses <research-dir>/index.yaml and <research-dir>/wiki/).",
    )
    parser.add_argument("--index-yaml", help="Explicit path to index.yaml (overrides --research-dir).")
    parser.add_argument("--wiki-dir", help="Explicit path to wiki/ (overrides --research-dir).")
    parser.add_argument("--output", help="Output path (default: <research-dir>/index.md).")
    args = parser.parse_args()

    if args.research_dir:
        research_dir = Path(args.research_dir)
        index_yaml_path = Path(args.index_yaml) if args.index_yaml else research_dir / "index.yaml"
        wiki_dir = Path(args.wiki_dir) if args.wiki_dir else research_dir / "wiki"
        output = Path(args.output) if args.output else research_dir / "index.md"
    else:
        if not args.index_yaml or not args.output:
            raise SystemExit("Pass --research-dir, or both --index-yaml and --output.")
        index_yaml_path = Path(args.index_yaml)
        wiki_dir = Path(args.wiki_dir) if args.wiki_dir else index_yaml_path.parent / "wiki"
        output = Path(args.output)

    if not index_yaml_path.is_file():
        raise SystemExit(f"index.yaml not found: {index_yaml_path}")

    md = build_md(index_yaml_path, wiki_dir)
    output.write_text(md)
    print(f"wrote {output} ({len(md)} bytes)")


if __name__ == "__main__":
    main()
